url: "https://alexmazansky.com"
analytics: true

collections:
  projects:
    output: false
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title

plugins:
 - jekyll-target-blank
